---
abstract: 'Parse XML Chunks Via LibXML SAX'
author:
  - 'Daisuke Maki C<< <daisuke@endeworks.jp> >>'
build_requires:
  Test::Compile: 0
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.76'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: XML-LibXML-SAX-ChunkParser
no_index:
  directory:
    - inc
    - t
requires:
  XML::LibXML: 1.66
  XML::SAX: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.00002
