---
abstract: 'Parse XML Chunks Via LibXML SAX'
author:
  - 'Daisuke Maki C<< <daisuke@endeworks.jp> >>'
build_requires:
  ExtUtils::MakeMaker: 6.36
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.04'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: XML-LibXML-SAX-ChunkParser
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  XML::LibXML: 1.66
  XML::SAX: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.00005
